name: Build and Test
on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install libsodium (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libsodium-dev
      - name: Install libsodium (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install libsodium
      - name: Install libsodium (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $ErrorActionPreference = 'Stop'
          $libsodiumVersion = "1.0.18-stable"
          $libsodiumUrl = "https://download.libsodium.org/libsodium/releases/libsodium-$libsodiumVersion-msvc.zip"
          Invoke-WebRequest -Uri $libsodiumUrl -OutFile libsodium.zip
          Expand-Archive -Path libsodium.zip -DestinationPath libsodium
          echo "SODIUM_LIB_DIR=$env:GITHUB_WORKSPACE\libsodium\x64\Release\v142\dynamic" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "SODIUM_INCLUDE_DIR=$env:GITHUB_WORKSPACE\libsodium\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "$env:GITHUB_WORKSPACE\libsodium\x64\Release\v142\dynamic" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Set up environment for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
      - name: Set up environment for macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I/usr/local/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/local/lib" >> $GITHUB_ENV
      - name: Set up environment for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "CGO_ENABLED=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - name: Test
        run: go test -v ./...